name: Continuous Integration

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build FrontEnd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          sparse-checkout: |
            .github
            src
      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./src/frontEnd/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if:
          steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ./src/frontEnd
