name: Continuous Integration

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: FrontEnd
    runs-on: ubuntu-latest
    steps:
      - name: Enter password to connect through SSH
        uses: step-security/wait-for-secrets@v1
        id: wait-for-secrets
        with:
          secrets: |
            PASSWORD: 
              name: 'Password to connect through SSH'
              description: 'Necessary password to connect through SSH'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          sparse-checkout: |
            .github
            src
      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./src/frontEnd
      - name: Build
        run: npm run build
        working-directory: ./src/frontEnd
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Stop frontend
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "$echo ${{ steps.wait-for-secrets.outputs.PASSWORD }} | sudo -S systemctl stop myCV.service && exit"
      - name: Update frontend
        run: scp -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/myCV
        working-directory: ./src/frontEnd
      - name: Start frontend
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl start myCV.service && exit"
